server:
  port: 8050

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: anhbopcolen
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create-drop  # for development
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        types:
          print:
            banner: false

  # Jackson configuration for proper JSON handling
  jackson:
    serialization:
      write-dates-as-timestamps: false

# Logging
logging:
  level:
    com.example.vrproutingbackend: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE